### ISSUE TITLE
A few questions - Connecting the Dots

### ISSUE THREAD

**Issue by chrismalek** [gu-io/gu#41]
I am looking for a front-end framework where I can do most of my development in Go and stay away from Javascript as much as possible. I came across this library and I have been reading the docs. Thank you for taking the time to put together the docs. There are still a few pieces that I can't connect the dots on with this package.

* I don't seem to understand what all the `.go` files are for. There are `*_bundle.go` files and `.generate.go` files littered throughout. That looks like some sort of go generation tool. I don't have any experience with that so I have some reading to do there. Which of these files do we use to modify code?
* I see maybe there is a `gu generate` command but I do not see that documented anywhere on what actually happens and when to use it in the development cycle. Does the `generate` command create/modify the go files then compile to js?
* GopherJS is used as the "driver" but I don't see how to connect the gopherJS into this.  Can I use `gopherjs build {appname.go}`
* I wonder if you had a look at [vecty](https://github.com/gopherjs/vecty). And have any thoughts on how gu differs from that. I have tried to do some evaluation. However, there are no docs and it seems not to support go modules so I have not been able to fully kick the tires on it.

Thanks and have a great day!

**Comment by influx6** [comment]
@chrismalek Hi, thanks for checking out the package, i must confess that the project is rather behind alot, and i would even rather advice to go with [Vecty](https://github.com/gopherjs/vecty) as it's more maintained, have unable to move further on this project due to time constraints.

Now to your questions:

1. The `.generate.go` files exists to generate the `*_bundle.go` files which will bundle your `*.css` and `*.html` into a `.go` file to be included in the final javascript to be created. This was meant to provide complete code bundling with assets without having to rely on setting such up using a fileserver if so desired.

2. The `gu generate` is there to create boiler plate code for you to simplify your life, the idea was to reduce the amound of setup code you had to write by hand. The idea was to provide a pluggable rendering layer which is not coupled to the code, so you could follow the instructions in https://github.com/gu-io/box, then naviagate into the `driver/js` directory and use `gopherjs build main.go` to generate a gopherjs javascript file containing the rendering setup to work.

People have found vecty more solid, and I would eagerly advice you to use it instead of thi.s
