### ISSUE TITLE
Implement listener for DOM node removals 

### ISSUE THREAD

**Issue by influx6** [gu-io/gu#8]
We need an efficient way to get notification of removals of rendering nodes, to ensure we are able to issue unmount calls. The resource definition easily handles notification for mounting majorly called for the browser DOM and but due to the fragmentation we need to have a system that works. 

Main approach should use MutationObservers

**Comment by gedw99** [comment]
In the gu-x i have a design to achieve that in the "store folder"
Have a look at the readme.

**Comment by influx6** [comment]
Alright

**Comment by joeblew99** [comment]
Noms is a new style of database.
Sure you have seen it.

Might be useful as it is the only one to support conflict management and is looking really good

**Comment by influx6** [comment]
Ya this issue is related to the browser DOM nodes and not db. I need to
know when a dom node gets removed. But the methods are somewhat scattered.

**Comment by gedw99** [comment]
ah the old reflux thing.. :)

**Comment by influx6** [comment]
I guess I will go with MutatioObservers and let older browsers not support it.

**Comment by gedw99** [comment]
makes sense. These days you design for evergreen, not IE 7 , etc.

Also I think though that its easy to do it a different way using Materialised views model that i wrote about and explained really badly i guess ) in the gu-x docs.. Your moving the reflux responsibilty into a UNidirectional DAG, so you no longer need mutation Observers at all. Its much easier to program it if your using the system too. This is where its all gone for big data and yet to find its way to the front end like many things. Reflex was a first step.

You should consider it, because its exactly what murlok has conceptually done also.
The HTML is templated outside the browser, and so they just shuve up teh diff into the web View.
Changes are driven by changing data in the data store, and the materialised views automaticallly change the DATA, NOT the view ! thats the critical difference.

You can have Materialised views on memory in the browser, but these days you really dont have to.
A simple stupid table in indexDB etc will do.

Then, ALL of the state change ONYL happens in this Database and NOWHERE else.

**Comment by influx6** [comment]
Ya, the this is just to provide a unmount for individual views. Gu never changes internal DOM based on browser changes, except for listening to events from input tags.

**Comment by influx6** [comment]
Luckily to reduce calling directly into the DOM. Have added event converters for gopherjs and will be working for one for the other drivers, so the user never deals with the js object directly but have all data pulled into a go struct.

https://github.com/gu-io/gu/blob/feature/apps/drivers/gopherjs/events.go

**Comment by influx6** [comment]
But as I said, this feature is becoming less important and more of a feature completion requirement.

**Comment by influx6** [comment]
Will kill this issue for now, if we later decide to had it up again then i will reopen it.

**Comment by gedw99** [comment]
Wow. Have to explain it to me when your ready. Definitely curious.

Did the murlok guy contact you by any chance ? I asked him to touch base
with you to see where you can collaborate. I am still away on holidays and
I can't help on the iOS and android drivers because my boss is pushing on
me getting stuff out

**Comment by influx6** [comment]
Na not yet. I guess he his busy as well. No problem
